### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by dany20mh** [mtniehaus/AutopilotBranding#5]
Hi,

Is it possible to add the "Scale and Layout" setting as well to this so we can set the default, for example, to 100% for all the users?

**Comment by boivinx7** [comment]
Hi there, I have the solution to this it's an easy one,
That said, I do not recommend that you do so. Because once you set it by script non admins cannot change it themselves.
I have it for a while in my SCCM image and it was causing more issues then fixes.

it would be something like so
`# STEP X: Set DPI Scalling to 100
Write-Host "Turning off (old) Edge desktop shortcut"

reg.exe load "HKLM\DEFAULT" c:\users\default\ntuser.dat | Out-Host

reg.exe add "HKLM\DEFAULT\Control Panel\Desktop" /v LogPixels /t REG_DWORD /d 96 /f /reg:64 | Out-Host
reg.exe add "HKLM\DEFAULT\Control Panel\Desktop" /v Win8DpiScaling /t REG_DWORD /d 0 /f /reg:64 | Out-Host

reg.exe unload "HKLM\DEFAULT" | Out-Host`

Be sure to test first

References:
https://scribbleghost.net/2018/06/25/customize-windows-10-default-user-profile/
https://www.tenforums.com/tutorials/5990-change-dpi-scaling-level-displays-windows-10-a.html

**Comment by dany20mh** [comment]
@boivinx7 
Thanks, I will give it a try.
